# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "apartment_ratings"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["gregory"]
  s.date = "2014-07-08"
  s.description = "Ruby client for ApartmentRating API"
  s.email = "greg2502@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rubocop.yml",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "lib/apartment_ratings.rb",
    "lib/apartment_ratings/address.rb",
    "lib/apartment_ratings/client.rb",
    "lib/apartment_ratings/complex.rb",
    "lib/apartment_ratings/configuration.rb",
    "lib/apartment_ratings/review.rb",
    "lib/apartment_ratings/reviews/rating.rb",
    "lib/apartment_ratings/reviews/response.rb",
    "spec/apartment_ratings/address_spec.rb",
    "spec/apartment_ratings/client_spec.rb",
    "spec/apartment_ratings/complex_spec.rb",
    "spec/apartment_ratings/review_spec.rb",
    "spec/apartment_ratings/reviews/rating_spec.rb",
    "spec/apartment_ratings/reviews/response_spec.rb",
    "spec/apartment_ratings_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/gregory/apartment_ratings"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Ruby client for ApartmentRating API"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hashie>, [">= 0"])
      s.add_runtime_dependency(%q<faraday>, ["~> 0.9.0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
      s.add_development_dependency(%q<rr>, ["~> 1.1.2"])
      s.add_development_dependency(%q<rspec>, ["~> 3.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<rubocop>, [">= 0.21.0"])
    else
      s.add_dependency(%q<hashie>, [">= 0"])
      s.add_dependency(%q<faraday>, ["~> 0.9.0"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<rr>, ["~> 1.1.2"])
      s.add_dependency(%q<rspec>, ["~> 3.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<rubocop>, [">= 0.21.0"])
    end
  else
    s.add_dependency(%q<hashie>, [">= 0"])
    s.add_dependency(%q<faraday>, ["~> 0.9.0"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<rr>, ["~> 1.1.2"])
    s.add_dependency(%q<rspec>, ["~> 3.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<rubocop>, [">= 0.21.0"])
  end
end

